name: Backup MySQL Database

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Configurar Docker
        run: docker-compose up -d

      - name: Dar permisos de ejecución al script de backup
        run: chmod +x backup.sh

      - name: Ejecutar el script de backup
        run: ./backup.sh
        
      - name: Verificar si se generó el backup
        run: ls -l backups/

      - name: Subir backups al repositorio
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/22041154/mysql-backups.git
          git add backups/backup_*.sql
          git commit -m "Backup automático $(date)"
          git push origin main

