name: Backup MySQL Database

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Iniciar contenedor MySQL
        run: |
          docker-compose up -d
          sleep 20  # Esperar a que el contenedor inicie correctamente

      - name: Dar permisos de ejecución al script
        run: chmod +x backup.sh

      - name: Ejecutar Backup de MySQL
        run: ./backup.sh
      - name: Verificar ubicación de backups
        run: find / -name "backup_*.sql" 2>/dev/null

      - name: Subir backups al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add backups/backup_*.sql
          git commit -m "Backup automático $(date)"
          git push