name: Backup MySQL Database

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Configurar Docker
        run: docker-compose up -d

      - name: Ejecutar el script de backup
        run: ./backup.sh

      - name: Verificar si el backup se generó
        run: ls -lh backups/ || echo "No se encontraron backups"

      - name: Subir backups al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add backups/backup_*.sql
          git commit -m "Backup automático $(date)" || echo "No hay cambios que subir"
          git push || echo "No hay cambios que subir"
